# Generated by Django 3.1.2 on 2020-10-27 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201027_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='task',
            name='comment',
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.task')),
            ],
        ),
        migrations.CreateModel(
            name='SubTaskComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('subtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subtask')),
            ],
        ),
    ]
