# Generated by Django 3.1.2 on 2020-10-28 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201028_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='space',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.space'),
        ),
    ]
