# Generated by Django 3.1.2 on 2020-10-28 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201028_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.space'),
        ),
    ]
